'use strict';

function createEmptyEquippedParts() {
  return EQUIPMENT_SLOTS.reduce((slots, type) => {
    slots[type] = null;
    return slots;
  }, {});
}

function createDifficultyStatsMap() {
  return DIFFICULTY_ORDER.reduce((stats, key) => {
    stats[key] = 0;
    return stats;
  }, {});
}

function createDefaultStats() {
  return {
    totalRaces: 0,
    totalWins: 0,
    totalLosses: 0,
    currentStreak: 0,
    bestStreak: 0,
    falseStartCount: 0,
    falseStartStreak: 0,
    secondPlaceStreak: 0,
    fifthPlaceStreak: 0,
    partsPurchasedCount: 0,
    highestCash: 1500,
    winsByDifficulty: createDifficultyStatsMap(),
    bestStreakByDifficulty: createDifficultyStatsMap(),
    hasFilledAllSlots: false,
    hasLowCashAfterRace: false,
    hasFinishedLast: false,
    hasNightmareSlowReactionWin: false,
    hasNightmareGlassCannonWin: false,
    hasNightmareStableWin: false,
    hasWonAfterSecondPlaceStreak: false,
    wonWithBuildAchievements: [],
    wonWithSpecialParts: [],
  };
}

function createDefaultAchievementsState() {
  return {
    completed: {},
    lastUnlocked: [],
  };
}

const gameState = {
  phase: 'idle',
  cash: 1500,
  raceCount: 0,
  lastRank: '-',
  bestReactionTime: null,
  lastReactionTime: null,
  currentWinStreak: 0,
  bestWinStreak: 0,
  difficulty: DEFAULT_DIFFICULTY,
  ready: false,
  greenAt: 0,
  reactionTime: null,
  playerStarted: false,
  countdownTimers: [],
  raceTimer: null,
  raceStartedAt: 0,
  lastRaceTickAt: 0,
  raceAccumulator: 0,
  shopItems: [],
  panelReturnPhase: 'idle',
  activePage: 'race',
  atlasFilter: 'all',
  inventory: [],
  equippedParts: createEmptyEquippedParts(),
  nextPartId: 1,
  cars: [],
  materials: [],
  craftingRecipes: [],
  player: { ...BASE_PLAYER_STATS },
  stats: createDefaultStats(),
  achievements: createDefaultAchievementsState(),
  achievementToastQueue: [],
  achievementToastTimer: null,
  noticeModalConfig: null,
  storageWriteBlockedReason: '',
};

const el = {
  registerBtn: document.getElementById('registerBtn'),
  startBtn: document.getElementById('startBtn'),
  nextBtn: document.getElementById('nextBtn'),
  saveBtn: document.getElementById('saveBtn'),
  loadBtn: document.getElementById('loadBtn'),
  restartBtn: document.getElementById('restartBtn'),
  tabs: Array.from(document.querySelectorAll('.page-tabs button')),
  pages: Array.from(document.querySelectorAll('.app-page')),
  lanes: document.getElementById('lanes'),
  shopPanel: document.getElementById('shopPanel'),
  shopBody: document.getElementById('shopBody'),
  garageSlotsBody: document.getElementById('garageSlotsBody'),
  tuningEquippedBody: document.getElementById('tuningEquippedBody'),
  tuningUnequippedBody: document.getElementById('tuningUnequippedBody'),
  difficultyChoices: document.getElementById('difficultyChoices'),
  difficultyOpenBtn: document.getElementById('difficultyOpenBtn'),
  difficultyCloseBtn: document.getElementById('difficultyCloseBtn'),
  difficultyOpenButtons: Array.from(document.querySelectorAll('[data-action="open-difficulty"]')),
  difficultyModal: document.getElementById('difficultyModal'),
  noticeModal: document.getElementById('noticeModal'),
  noticeModalTitle: document.getElementById('noticeModalTitle'),
  noticeModalMessage: document.getElementById('noticeModalMessage'),
  noticeModalCloseBtn: document.getElementById('noticeModalCloseBtn'),
  noticeModalCancelBtn: document.getElementById('noticeModalCancelBtn'),
  noticeModalConfirmBtn: document.getElementById('noticeModalConfirmBtn'),
  difficultyCurrentName: document.getElementById('difficultyCurrentName'),
  difficultyCurrentMeta: document.getElementById('difficultyCurrentMeta'),
  atlasBody: document.getElementById('atlasBody'),
  atlasDifficultyText: document.getElementById('atlasDifficultyText'),
  atlasCashStat: document.getElementById('atlasCashStat'),
  atlasFilters: Array.from(document.querySelectorAll('[data-atlas-filter]')),
  atlasSummaryText: document.getElementById('atlasSummaryText'),
  logOutput: document.getElementById('logOutput'),
  redLight: document.getElementById('redLight'),
  yellowLight: document.getElementById('yellowLight'),
  greenLight: document.getElementById('greenLight'),
  lightLabel: document.getElementById('lightLabel'),
  phaseText: document.getElementById('phaseText'),
  raceTierText: document.getElementById('raceTierText'),
  entryFeeText: document.getElementById('entryFeeText'),
  bestReactionText: document.getElementById('bestReactionText'),
  winStreakText: document.getElementById('winStreakText'),
  raceRoundText: document.getElementById('raceRoundText'),
  opponentPowerText: document.getElementById('opponentPowerText'),
  raceReportEmptyText: document.getElementById('raceReportEmptyText'),
  raceReportStats: document.getElementById('raceReportStats'),
  raceCurrentWinStreakStat: document.getElementById('raceCurrentWinStreakStat'),
  raceBestWinStreakStat: document.getElementById('raceBestWinStreakStat'),
  engineStat: document.getElementById('engineStat'),
  tireStat: document.getElementById('tireStat'),
  gearboxStat: document.getElementById('gearboxStat'),
  stabilityStat: document.getElementById('stabilityStat'),
  weightStat: document.getElementById('weightStat'),
  hpStat: document.getElementById('hpStat'),
  cashStat: document.getElementById('cashStat'),
  raceCountStat: document.getElementById('raceCountStat'),
  lastRankStat: document.getElementById('lastRankStat'),
  lastReactionStat: document.getElementById('lastReactionStat'),
  currentVehicleText: document.getElementById('currentVehicleText'),
  resultMessage: document.getElementById('resultMessage'),
  shopCashStat: document.getElementById('shopCashStat'),
  tuningCashStat: document.getElementById('tuningCashStat'),
  profileCashStat: document.getElementById('profileCashStat'),
  profileDifficultyName: document.getElementById('profileDifficultyName'),
  profileDifficultyMeta: document.getElementById('profileDifficultyMeta'),
  achievementsBody: document.getElementById('achievementsBody'),
  achievementsCountText: document.getElementById('achievementsCountText'),
  statsTotalRaces: document.getElementById('statsTotalRaces'),
  statsTotalWins: document.getElementById('statsTotalWins'),
  statsTotalLosses: document.getElementById('statsTotalLosses'),
  statsCurrentStreak: document.getElementById('statsCurrentStreak'),
  statsBestStreak: document.getElementById('statsBestStreak'),
  statsDifficultyWins: document.getElementById('statsDifficultyWins'),
  statsDifficultyBestStreaks: document.getElementById('statsDifficultyBestStreaks'),
  statsHighestCash: document.getElementById('statsHighestCash'),
  statsCollectionProgress: document.getElementById('statsCollectionProgress'),
  versionText: document.getElementById('versionText'),
  versionNote: document.getElementById('versionNote'),
  achievementToast: document.getElementById('achievementToast'),
};
