'use strict';

function createEmptyEquippedParts() {
  return EQUIPMENT_SLOTS.reduce((slots, type) => {
    slots[type] = null;
    return slots;
  }, {});
}

const gameState = {
  phase: 'idle',
  cash: 1500,
  raceCount: 0,
  lastRank: '-',
  difficulty: DEFAULT_DIFFICULTY,
  ready: false,
  greenAt: 0,
  reactionTime: null,
  playerStarted: false,
  countdownTimers: [],
  raceTimer: null,
  raceStartedAt: 0,
  lastRaceTickAt: 0,
  raceAccumulator: 0,
  shopItems: [],
  panelReturnPhase: 'idle',
  activePage: 'race',
  restartArmed: false,
  restartArmedTimer: null,
  inventory: [],
  equippedParts: createEmptyEquippedParts(),
  nextPartId: 1,
  cars: [],
  materials: [],
  craftingRecipes: [],
  player: { ...BASE_PLAYER_STATS },
};

const el = {
  registerBtn: document.getElementById('registerBtn'),
  startBtn: document.getElementById('startBtn'),
  nextBtn: document.getElementById('nextBtn'),
  saveBtn: document.getElementById('saveBtn'),
  loadBtn: document.getElementById('loadBtn'),
  restartBtn: document.getElementById('restartBtn'),
  tabs: Array.from(document.querySelectorAll('.page-tabs button')),
  pages: Array.from(document.querySelectorAll('.app-page')),
  lanes: document.getElementById('lanes'),
  shopPanel: document.getElementById('shopPanel'),
  shopBody: document.getElementById('shopBody'),
  garageSlotsBody: document.getElementById('garageSlotsBody'),
  tuningEquippedBody: document.getElementById('tuningEquippedBody'),
  tuningUnequippedBody: document.getElementById('tuningUnequippedBody'),
  storageInventoryBody: document.getElementById('storageInventoryBody'),
  storageMaterialsBody: document.getElementById('storageMaterialsBody'),
  difficultyChoices: document.getElementById('difficultyChoices'),
  difficultyOpenBtn: document.getElementById('difficultyOpenBtn'),
  difficultyCloseBtn: document.getElementById('difficultyCloseBtn'),
  difficultyModal: document.getElementById('difficultyModal'),
  difficultyCurrentName: document.getElementById('difficultyCurrentName'),
  difficultyCurrentMeta: document.getElementById('difficultyCurrentMeta'),
  atlasBody: document.getElementById('atlasBody'),
  atlasDifficultyText: document.getElementById('atlasDifficultyText'),
  atlasCashStat: document.getElementById('atlasCashStat'),
  logOutput: document.getElementById('logOutput'),
  redLight: document.getElementById('redLight'),
  yellowLight: document.getElementById('yellowLight'),
  greenLight: document.getElementById('greenLight'),
  lightLabel: document.getElementById('lightLabel'),
  phaseText: document.getElementById('phaseText'),
  raceTierText: document.getElementById('raceTierText'),
  entryFeeText: document.getElementById('entryFeeText'),
  opponentPowerText: document.getElementById('opponentPowerText'),
  engineStat: document.getElementById('engineStat'),
  tireStat: document.getElementById('tireStat'),
  gearboxStat: document.getElementById('gearboxStat'),
  stabilityStat: document.getElementById('stabilityStat'),
  weightStat: document.getElementById('weightStat'),
  hpStat: document.getElementById('hpStat'),
  cashStat: document.getElementById('cashStat'),
  raceCountStat: document.getElementById('raceCountStat'),
  lastRankStat: document.getElementById('lastRankStat'),
  currentVehicleText: document.getElementById('currentVehicleText'),
  resultMessage: document.getElementById('resultMessage'),
  shopCashStat: document.getElementById('shopCashStat'),
  tuningCashStat: document.getElementById('tuningCashStat'),
  storageCashStat: document.getElementById('storageCashStat'),
};
